### ISSUE TITLE
Play nicely with combineResolvers

### ISSUE THREAD

**Issue by johnnyoshika** [JCMais/graphql-yup-middleware#7]
Is there a way to make this middleware compatible with `combineResolvers` from https://www.npmjs.com/package/graphql-resolvers?

`combineResolvers` expects an array of resolvers, so this currently works:

```
  Mutation: {
    createFoo: {
      validationSchema: yup.object().shape({
        name: yup.string().trim().required('Name is required'),
      }),
      resolve: combineResolvers(
        isAuthenticated,
        async (
          _,
          { name }
        ) => ({
          // do something
        }),
      ),
    },
  },
```

You see that I have an `isAuthenticated` resolver function that checks whether the actor is authenticated. This acts as a middleware. However, I can't get it to run before the yup middleware. So the way it works now, it does the validation first before checking whether the actor is authenticated, which is backwards.

It would be nice if the yup middleware supported functions that returned a `validationSchema` so that I can do something like this:

```
  Mutation: {
    createFoo: {
      combineResolvers(
        isAuthenticated,
        (parent, args, context) => yup.object().shape({
          name: yup.string().trim().required('Name is required'),
        }),
        async (
          _,
          { name }
        ) => ({
          // do something
        }),
      ),
    },
  },
```

**Comment by JCMais** [comment]
You probably better off using only `combineResolvers` in this case, since it already acts as an "middleware" of sorts.

You can write a custom resolve function which is responsible for validating the input based on the given yup schema, per your example, it would be something like
```
  Mutation: {
    createFoo: {
      combineResolvers(
        isAuthenticated,
        hasValidInputArgs(yup.object().shape({
          name: yup.string().trim().required('Name is required'),
        })),
        validationAwareResolver(async (
          _,
          { name }
        ) => ({
          // do something
        })),
      ),
    },
  },
```

Then on `hasValidInputArgs` you could return a resolver which validates the query based on the given schema, and return a custom object saying if it's valid or not, including error messages if not.

Then `validationAwareResolver` acts as a wrapper around your "real" resolver, it should end the request with the error message returned from the validation step in case the validation failed, otherwise it runs the resolver passed as argument and returns their value.

If you feel this package would be a good place for such helper functions, feel free to open a PR.

**Comment by johnnyoshika** [comment]
@JCMais You're absolutely right! Thanks for your feedback.

**Comment by johnnyoshika** [comment]
If anyone is interested in my solution, here's what I did:

validate.ts:

```
import * as yup from 'yup';
import { skip } from 'graphql-resolvers';
import { UserInputError } from 'apollo-server';

const formatMessage = (errors: yup.ValidationError[]) =>
  !errors.length
    ? 'Error encountered.'
    : errors.length === 1
    ? `${errors[0]}.`
    : `${errors.length} Errors: ${errors
        .map((e, i) => `${i + 1}) ${e}.`)
        .join(' ')}`;

const validate = (schema: yup.ObjectSchema) => async (_, args) => {
  try {
    await schema.validate(args, {
      abortEarly: false,
    });
    return skip;
  } catch (error) {
    throw new UserInputError(formatMessage(error.errors));
  }
};

export default validate;
```

my resolver file:
```
import validate from './validate';
import { combineResolvers } from 'graphql-resolvers';
  ...
  Mutation: {
    createEndpoint: combineResolvers(
      validate(
        yup.object().shape({
          name: yup.string().trim().required('Name is required'),
        }),
      ),

      // Real resolver. This will only be called if validation passes.
      async (
        _,
        { name },
      ) => ({
        // do something
      }),
    ),
  },
  ...
```
